In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.neighbors import KDTree
import gdown
from PIL import Image, ImageOps
from scipy.spatial import distance
from scipy.stats import multivariate_normal
import seaborn as sns
import os
import json
from math import log
import os
from sklearn.neighbors import BallTree,DistanceMetric
from IPython.display import display
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [8]:
data = np.array(load_iris().data)
labels_pre = np.array(load_iris().target)
labels = []
for i in labels_pre:
    label_arr = np.zeros(3)
    label_arr[i] = 1
    labels.append(label_arr)
labels = np.array(labels)

#Normalización:
sc = MinMaxScaler()
sc.fit(data)
data = sc.transform(data)

n = data.shape[0]
m = data.shape[1]
indexes = np.arange(n)
x_train, x_oth, y_train, y_oth = train_test_split(data, labels, test_size=0.2)
x_test, x_validation, y_test, y_validation = train_test_split(x_oth, y_oth, test_size=0.5)

print(x_train)
print(x_test.shape)
print(x_validation.shape)
print(y_train.shape)
print(y_test.shape)
print(y_validation.shape)


[[0.80555556 0.66666667 0.86440678 1.        ]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.47222222 0.08333333 0.6779661  0.58333333]
 [0.22222222 0.70833333 0.08474576 0.125     ]
 [0.36111111 0.33333333 0.66101695 0.79166667]
 [0.58333333 0.375      0.55932203 0.5       ]
 [0.36111111 0.375      0.44067797 0.5       ]
 [0.66666667 0.41666667 0.71186441 0.91666667]
 [0.30555556 0.41666667 0.59322034 0.58333333]
 [0.47222222 0.41666667 0.6440678  0.70833333]
 [0.52777778 0.375      0.55932203 0.5       ]
 [0.44444444 0.41666667 0.69491525 0.70833333]
 [0.30555556 0.58333333 0.08474576 0.125     ]
 [0.44444444 0.41666667 0.54237288 0.58333333]
 [0.72222222 0.45833333 0.74576271 0.83333333]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.66666667 0.20833333 0.81355932 0.70833333]
 [0.61111111 0.5        0.69491525 0.79166667]
 [0.58333333 0.5        0.72881356 0.91666667]
 [0.13888889 0.41666667 0.06779661 0.08333333]
 [0.72222222 0.5        0.79661017 0.91666667]
 [0.80555556 

In [9]:
obj = dict()
obj["Train"] = {"Classes": y_train.tolist(), "Images": x_train.tolist()}
obj["Test"] = {"Classes": y_test.tolist(), "Images": x_test.tolist()}
obj["Validation"] = {"Classes": y_validation.tolist(), "Images": x_validation.tolist()}
with open("data.json", "w") as write_file:
    json.dump(obj, write_file)